apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  selector:
    matchLabels:
      app: php-app
  replicas: 1
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: kenzochernobyllabdocker
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
spec:
  type: LoadBalancer
  selector:
    app: php-app
  ports:
  - name: http
    port: 80
    targetPort: 80